### ISSUE TITLE
python3 compatibility

### ISSUE THREAD

**Issue by phaethon** [dh1tw/pyhamtools#9]
Are there any plans for python3 compatibility?

**Comment by dh1tw** [comment]
Hey, 
I still haven't started using Python3, since 100% of my code base is on Python2 and I have shifted for newer projects towards using [golang](https://golang.org/). This doesn't mean that PyHamtools won't support Python3 in the future, but for the moment, if nobody can assist me with a fork / pull request, it will remain Python2.

**Comment by phaethon** [comment]
OK, thanks for clarification.
